/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as LayoutOrdersRouteImport } from './routes/_layout/orders'
import { Route as LayoutOrderTrackingRouteImport } from './routes/_layout/order-tracking'
import { Route as LayoutCheckoutRouteImport } from './routes/_layout/checkout'
import { Route as LayoutCartRouteImport } from './routes/_layout/cart'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutStoreIndexRouteImport } from './routes/_layout/store/index'
import { Route as LayoutProductIndexRouteImport } from './routes/_layout/product/index'
import { Route as LayoutCategoryIndexRouteImport } from './routes/_layout/category/index'
import { Route as LayoutStoreOrderConfirmationRouteImport } from './routes/_layout/store/order-confirmation'
import { Route as LayoutStoreSlugRouteImport } from './routes/_layout/store/$slug'
import { Route as LayoutProductSlugRouteImport } from './routes/_layout/product/$slug'
import { Route as LayoutCategorySlugRouteImport } from './routes/_layout/category/$slug'
import { Route as LayoutProtectedProtectedRouteImport } from './routes/_layout/_protected/protected'
import { Route as LayoutProtectedProfileRouteImport } from './routes/_layout/_protected/profile'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutOrdersRoute = LayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrderTrackingRoute = LayoutOrderTrackingRouteImport.update({
  id: '/order-tracking',
  path: '/order-tracking',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCheckoutRoute = LayoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCartRoute = LayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStoreIndexRoute = LayoutStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductIndexRoute = LayoutProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoryIndexRoute = LayoutCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStoreOrderConfirmationRoute =
  LayoutStoreOrderConfirmationRouteImport.update({
    id: '/store/order-confirmation',
    path: '/store/order-confirmation',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutStoreSlugRoute = LayoutStoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductSlugRoute = LayoutProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategorySlugRoute = LayoutCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProtectedProtectedRoute =
  LayoutProtectedProtectedRouteImport.update({
    id: '/_protected/protected',
    path: '/protected',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProtectedProfileRoute = LayoutProtectedProfileRouteImport.update({
  id: '/_protected/profile',
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/about': typeof LayoutAboutRoute
  '/cart': typeof LayoutCartRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/order-tracking': typeof LayoutOrderTrackingRoute
  '/orders': typeof LayoutOrdersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/profile': typeof LayoutProtectedProfileRoute
  '/protected': typeof LayoutProtectedProtectedRoute
  '/category/$slug': typeof LayoutCategorySlugRoute
  '/product/$slug': typeof LayoutProductSlugRoute
  '/store/$slug': typeof LayoutStoreSlugRoute
  '/store/order-confirmation': typeof LayoutStoreOrderConfirmationRoute
  '/category/': typeof LayoutCategoryIndexRoute
  '/product/': typeof LayoutProductIndexRoute
  '/store/': typeof LayoutStoreIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof LayoutAboutRoute
  '/cart': typeof LayoutCartRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/order-tracking': typeof LayoutOrderTrackingRoute
  '/orders': typeof LayoutOrdersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof LayoutIndexRoute
  '/profile': typeof LayoutProtectedProfileRoute
  '/protected': typeof LayoutProtectedProtectedRoute
  '/category/$slug': typeof LayoutCategorySlugRoute
  '/product/$slug': typeof LayoutProductSlugRoute
  '/store/$slug': typeof LayoutStoreSlugRoute
  '/store/order-confirmation': typeof LayoutStoreOrderConfirmationRoute
  '/category': typeof LayoutCategoryIndexRoute
  '/product': typeof LayoutProductIndexRoute
  '/store': typeof LayoutStoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/cart': typeof LayoutCartRoute
  '/_layout/checkout': typeof LayoutCheckoutRoute
  '/_layout/order-tracking': typeof LayoutOrderTrackingRoute
  '/_layout/orders': typeof LayoutOrdersRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_protected/profile': typeof LayoutProtectedProfileRoute
  '/_layout/_protected/protected': typeof LayoutProtectedProtectedRoute
  '/_layout/category/$slug': typeof LayoutCategorySlugRoute
  '/_layout/product/$slug': typeof LayoutProductSlugRoute
  '/_layout/store/$slug': typeof LayoutStoreSlugRoute
  '/_layout/store/order-confirmation': typeof LayoutStoreOrderConfirmationRoute
  '/_layout/category/': typeof LayoutCategoryIndexRoute
  '/_layout/product/': typeof LayoutProductIndexRoute
  '/_layout/store/': typeof LayoutStoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/order-tracking'
    | '/orders'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/profile'
    | '/protected'
    | '/category/$slug'
    | '/product/$slug'
    | '/store/$slug'
    | '/store/order-confirmation'
    | '/category/'
    | '/product/'
    | '/store/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/cart'
    | '/checkout'
    | '/order-tracking'
    | '/orders'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/profile'
    | '/protected'
    | '/category/$slug'
    | '/product/$slug'
    | '/store/$slug'
    | '/store/order-confirmation'
    | '/category'
    | '/product'
    | '/store'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/about'
    | '/_layout/cart'
    | '/_layout/checkout'
    | '/_layout/order-tracking'
    | '/_layout/orders'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_layout/'
    | '/_layout/_protected/profile'
    | '/_layout/_protected/protected'
    | '/_layout/category/$slug'
    | '/_layout/product/$slug'
    | '/_layout/store/$slug'
    | '/_layout/store/order-confirmation'
    | '/_layout/category/'
    | '/_layout/product/'
    | '/_layout/store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/order-tracking': {
      id: '/_layout/order-tracking'
      path: '/order-tracking'
      fullPath: '/order-tracking'
      preLoaderRoute: typeof LayoutOrderTrackingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/checkout': {
      id: '/_layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof LayoutCheckoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cart': {
      id: '/_layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof LayoutCartRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/store/': {
      id: '/_layout/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof LayoutStoreIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/product/': {
      id: '/_layout/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof LayoutProductIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/category/': {
      id: '/_layout/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof LayoutCategoryIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/store/order-confirmation': {
      id: '/_layout/store/order-confirmation'
      path: '/store/order-confirmation'
      fullPath: '/store/order-confirmation'
      preLoaderRoute: typeof LayoutStoreOrderConfirmationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/store/$slug': {
      id: '/_layout/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof LayoutStoreSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/product/$slug': {
      id: '/_layout/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof LayoutProductSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/category/$slug': {
      id: '/_layout/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof LayoutCategorySlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_protected/protected': {
      id: '/_layout/_protected/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof LayoutProtectedProtectedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_protected/profile': {
      id: '/_layout/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProtectedProfileRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutCartRoute: typeof LayoutCartRoute
  LayoutCheckoutRoute: typeof LayoutCheckoutRoute
  LayoutOrderTrackingRoute: typeof LayoutOrderTrackingRoute
  LayoutOrdersRoute: typeof LayoutOrdersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProtectedProfileRoute: typeof LayoutProtectedProfileRoute
  LayoutProtectedProtectedRoute: typeof LayoutProtectedProtectedRoute
  LayoutCategorySlugRoute: typeof LayoutCategorySlugRoute
  LayoutProductSlugRoute: typeof LayoutProductSlugRoute
  LayoutStoreSlugRoute: typeof LayoutStoreSlugRoute
  LayoutStoreOrderConfirmationRoute: typeof LayoutStoreOrderConfirmationRoute
  LayoutCategoryIndexRoute: typeof LayoutCategoryIndexRoute
  LayoutProductIndexRoute: typeof LayoutProductIndexRoute
  LayoutStoreIndexRoute: typeof LayoutStoreIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutCartRoute: LayoutCartRoute,
  LayoutCheckoutRoute: LayoutCheckoutRoute,
  LayoutOrderTrackingRoute: LayoutOrderTrackingRoute,
  LayoutOrdersRoute: LayoutOrdersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProtectedProfileRoute: LayoutProtectedProfileRoute,
  LayoutProtectedProtectedRoute: LayoutProtectedProtectedRoute,
  LayoutCategorySlugRoute: LayoutCategorySlugRoute,
  LayoutProductSlugRoute: LayoutProductSlugRoute,
  LayoutStoreSlugRoute: LayoutStoreSlugRoute,
  LayoutStoreOrderConfirmationRoute: LayoutStoreOrderConfirmationRoute,
  LayoutCategoryIndexRoute: LayoutCategoryIndexRoute,
  LayoutProductIndexRoute: LayoutProductIndexRoute,
  LayoutStoreIndexRoute: LayoutStoreIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
